-- In database/schema.sql

DROP TABLE IF EXISTS UNEMPLOYMENT_DATA;
CREATE TABLE UNEMPLOYMENT_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  UNEMPLOYMENT_RATE NUMERIC,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);

DROP TABLE IF EXISTS CRIME_DATA;
CREATE TABLE CRIME_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  NUMBER_OF_VICTIMS INT,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);

DROP TABLE IF EXISTS ELECTION_DATA;
CREATE TABLE ELECTION_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  WINNER TEXT,
  REGISTERED_VOTERS INT,
  VOTERS INT,
  PARTY_1 TEXT,
  VOTES_1 NUMERIC,
  PARTY_2 TEXT,
  VOTES_2 NUMERIC,
  PARTY_3 TEXT,
  VOTES_3 NUMERIC,
  PARTY_4 TEXT,
  VOTES_4 NUMERIC,
  PARTY_5 TEXT,
  VOTES_5 NUMERIC,
  PARTY_6 TEXT,
  VOTES_6 NUMERIC,
  PARTY_7 TEXT,
  VOTES_7 NUMERIC,
  PARTY_8 TEXT,
  VOTES_8 NUMERIC,
  PARTY_9 TEXT,
  VOTES_9 NUMERIC,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);

DROP TABLE IF EXISTS IMMIGRATION_DATA;
CREATE TABLE IMMIGRATION_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  IMMIGRATION_RATE NUMERIC,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);

DROP TABLE IF EXISTS POVERTY_DATA;
CREATE TABLE POVERTY_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  POVERTY_RATE NUMERIC,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);