-- In database/schema.sql

DROP TABLE IF EXISTS UNEMPLOYMENT_DATA;
CREATE TABLE UNEMPLOYMENT_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  UNEMPLOYMENT_RATE NUMERIC,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);

DROP TABLE IF EXISTS CRIME_DATA;
CREATE TABLE CRIME_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  NUMBER_OF_VICTIMS INT,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);

DROP TABLE IF EXISTS ELECTION_DATA;
CREATE TABLE ELECTION_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  WINNER TEXT,
  REGISTERED_VOTERS INT,
  VOTERS INT,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);

DROP TABLE IF EXISTS IMMIGRATION_DATA;
CREATE TABLE IMMIGRATION_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  IMMIGRATION_RATE NUMERIC,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);

DROP TABLE IF EXISTS POVERTY_DATA;
CREATE TABLE POVERTY_DATA (
  YEAR INT,
  DEPARTMENT_CODE TEXT,
  DEPARTMENT TEXT,
  POVERTY_RATE NUMERIC,
  PRIMARY KEY (YEAR, DEPARTMENT_CODE)
);